from pathlib import Path

p=Path('app/static/table-readability-v72.js')
s=p.read_text()
needle='''      /* Use the TV width instead of the old fixed 1810/1870px ceilings. */\n'''
insert='''      /* Background art is always the back plane. Hero/logo and table content\n         live in explicit higher stacking contexts so background artwork can\n         never visually layer over the team identity. A soft theme-colour\n         shield behind the hero prevents busy background detail showing through\n         transparent logo margins. */\n      #themedTeamBroadcast,#v55OfficeBroadcast,.v69-team-card{isolation:isolate!important}\n      #themedTeamBroadcast .bt-bg,#v55OfficeBroadcast .v55-office-bg,.v69-team-card .v69-card-bg{z-index:0!important;pointer-events:none!important}\n      #themedTeamBroadcast .bt-atmosphere,#v55OfficeBroadcast .v55-office-atmosphere,.v69-team-card .v69-card-atmosphere{z-index:1!important;pointer-events:none!important}\n      #themedTeamBroadcast .bt-header,#v55OfficeBroadcast .v55-office-brand,.v69-team-card .v69-brand{isolation:isolate!important;z-index:6!important}\n      #themedTeamBroadcast .bt-main,#v55OfficeBroadcast .v55-office-main,.v69-team-card .v69-main{z-index:5!important}\n      #themedTeamBroadcast .bt-header:before,#v55OfficeBroadcast .v55-office-brand:before,.v69-team-card .v69-brand:before{\n        content:"";position:absolute;inset:0 16%;z-index:0;pointer-events:none;\n        background:radial-gradient(ellipse at center,color-mix(in srgb,currentColor 0%,var(--bt-bg,#070706)) 0%,color-mix(in srgb,var(--bt-bg,#070706) 78%,transparent) 54%,transparent 82%)\n      }\n      #v55OfficeBroadcast .v55-office-brand:before{background:radial-gradient(ellipse at center,var(--v55-bg) 0%,color-mix(in srgb,var(--v55-bg) 78%,transparent) 54%,transparent 82%)}\n      .v69-team-card .v69-brand:before{background:radial-gradient(ellipse at center,var(--v69-bg) 0%,color-mix(in srgb,var(--v69-bg) 78%,transparent) 54%,transparent 82%)}\n      #themedTeamBroadcast .bt-hero,#themedTeamBroadcast .bt-wordmark,#v55OfficeBroadcast .v55-office-hero,#v55OfficeBroadcast .v55-office-wordmark,.v69-team-card .v69-hero,.v69-team-card .v69-team-name,.v69-team-card .v69-ranked{position:relative;z-index:2!important}\n\n'''
if insert not in s:
    if needle not in s: raise SystemExit('readability CSS insertion point missing')
    s=s.replace(needle,insert+needle,1)
p.write_text(s)
