from .base import LeaderboardSource

class SampleSource(LeaderboardSource):
    def fetch(self):
        return [
            {
                "rep_key": "aaron-hein",
                "rep_name": "Aaron Hein",
                "team": "Team Alpha",
                "team_lead": "Grady",
                "home_branch": "Spokane",
                "title": "Sales Rep",
                "hire_date": "2026-03-02",
                "issued_leads": 5,
                "pitched_leads": 3.5,
                "pitched_rate": 70.00,
                "sold_leads": 0.5,
                "close_rate": 10.00,
                "gross_split": 19271.06,
                "pending_split": 0,
                "net_split": 19271.06,
                "dpl": 3854.21,
                "sales_retention": 100.00,
                "avg_gross_sale": 38542,
                "avg_net_sale": 38542.12,
            },
            {
                "rep_key": "abigail-freund",
                "rep_name": "Abigail Freund",
                "team": "Team Bravo",
                "team_lead": "Lama",
                "home_branch": "Tri-Cities",
                "title": "Sales Rep",
                "hire_date": "2026-06-15",
                "issued_leads": 3.5,
                "pitched_leads": 2,
                "pitched_rate": 57.14,
                "sold_leads": 1.5,
                "close_rate": 42.86,
                "gross_split": 26458.08,
                "pending_split": 13260.98,
                "net_split": 13197.10,
                "dpl": 3770.60,
                "sales_retention": 49.88,
                "avg_gross_sale": 17639,
                "avg_net_sale": 8798.07,
            },
            {
                "rep_key": "aldonis-johnson",
                "rep_name": "Aldonis Johnson",
                "team": "Team Alpha",
                "team_lead": "Grady",
                "home_branch": "Vancouver",
                "title": "Sales Rep",
                "hire_date": "2025-09-29",
                "issued_leads": 6,
                "pitched_leads": 5.5,
                "pitched_rate": 91.67,
                "sold_leads": 3,
                "close_rate": 50.00,
                "gross_split": 120309.44,
                "pending_split": 45235.44,
                "net_split": 75074.00,
                "dpl": 12512.33,
                "sales_retention": 62.40,
                "avg_gross_sale": 40103,
                "avg_net_sale": 25024.67,
            },
            {
                "rep_key": "alex-oneill",
                "rep_name": "Alex Oneill",
                "team": "Team Bravo",
                "team_lead": "Lama",
                "home_branch": "Boise",
                "title": "Sales Rep",
                "hire_date": "2026-03-23",
                "issued_leads": 8,
                "pitched_leads": 6,
                "pitched_rate": 75.00,
                "sold_leads": 2,
                "close_rate": 25.00,
                "gross_split": 48800,
                "pending_split": 12000,
                "net_split": 36800,
                "dpl": 6100,
                "sales_retention": 75.40,
                "avg_gross_sale": 24400,
                "avg_net_sale": 18400,
            },
            {
                "rep_key": "maria-santos",
                "rep_name": "Maria Santos",
                "team": "Team Charlie",
                "team_lead": "Jorge",
                "home_branch": "Olympia",
                "title": "Sales Rep",
                "hire_date": "2026-05-01",
                "issued_leads": 7,
                "pitched_leads": 6,
                "pitched_rate": 85.71,
                "sold_leads": 2.5,
                "close_rate": 35.71,
                "gross_split": 71000,
                "pending_split": 9000,
                "net_split": 62000,
                "dpl": 8857.14,
                "sales_retention": 87.32,
                "avg_gross_sale": 28400,
                "avg_net_sale": 24800,
            },
            {
                "rep_key": "denis-roof",
                "rep_name": "Denis Roof",
                "team": "Team Charlie",
                "team_lead": "Jorge",
                "home_branch": "Tacoma",
                "title": "Sales Rep",
                "hire_date": "2026-07-20",
                "issued_leads": 4,
                "pitched_leads": 3,
                "pitched_rate": 75.00,
                "sold_leads": 1,
                "close_rate": 25.00,
                "gross_split": 22000,
                "pending_split": 3000,
                "net_split": 19000,
                "dpl": 4750,
                "sales_retention": 86.36,
                "avg_gross_sale": 22000,
                "avg_net_sale": 19000,
            },
        ]
